name: pr-agent

on:
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    name: Run PR Agent
    if: ${{ github.event.sender.type != 'Bot' }}
    steps:
      - id: pr-agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KAKERU_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_action.auto_describe: true
          github_action.auto_review:   true
          github_action.auto_improve:  true
          CONFIG.MODEL: gpt-4o
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS:      'Please use Japanese.日本語を使用してください。'
          PR_REVIEWER.EXTRA_INSTRUCTIONS:         'Please use Japanese.日本語を使用してください。'
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: 'Please use Japanese.日本語を使用してください。'